server:
  port: 5555

spring:
  cloud:
    config:
      uri:  http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-url: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    organizationservice: /org/**
    licensingservice: /license/**
