version: '2'
services:

  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DB: "eagle_eye_local"

  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver

  licensingservice:
    image: annamart/licensing-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "3306"